security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    
#    firewalls:
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
##            http_basic:
##                realm: "Secured Demo Area"
#            form_login:
#                login_path:  /login
#                check_path:  /login_check
#            logout:
#                path:   /logout
#                target: /hello/unknown

#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }

#    providers:
#        in_memory:
#            users:
#                eux:  { password: eux, roles: 'ROLE_USER' }
#                admin: { password: kitten, roles: 'ROLE_ADMIN' }

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            fos_facebook:
                  app_url: "http://apps.facebook.com/appName/"
                  server_url: "http://localhost/facebookApp/"
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                  handlers: ["fos_facebook.logout_handler"]
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
        
