hello:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
    
protected:
    pattern:  /admin/protected
    defaults: { _controller: AcmeHelloBundle:Admin:index }
    
#login:
#    pattern:   /login
#    defaults:  { _controller: AcmeHelloBundle:Admin:login }
#    
#login_check:
#    pattern:   /login_check
#
#
logout:
    pattern:   /logout

